export const Users = [
    {
    id: 1,
    name: "Chandler Bing",
    username: "Chandler Bing",
    email: "Cbing@test.com",
    profilePicture: "/assets/person/Chandler.jpg",
},
{
    id: 2,
    name: "Joey Tribbiani",
    username: "Joey Tribbiani",
    email: "JoeyT@test.com",
    profilePicture: "/assets/person/joey.jpg",
},
{
    id: 3,
    name: "Monica Geller",
    username: "Monica Geller",
    email: "Mgeller@test.com",
    profilePicture: "/assets/person/monica_geller.jpg",
},
{
  id: 4,
  name: "Phoebe Buffay",
  username: "Phoebe Buffay",
  email: "PhoebeB@test.com",
  profilePicture: "/assets/person/Phoebe.jpg",
},
{
  id: 5,
  name: "Rachel Green",
  username: "Rachel Green",
  email: "Rgreen@test.com",
  profilePicture: "/assets/person/rachel.jpg",
},
{
  id: 6,
  name: "Ross Geller",
  username: "Ross Geller",
  email: "Rgeller@test.com",
  profilePicture: "/assets/person/RossGeller.jpg",
},
];

// export const Usersonline = [
//   {
//     id: 1,
//     name: "Chandler Bing",
//     username: "Cbing",
//     email: "Cbing@test.com",
//     profilePicture: "/assets/person/Chandler.jpg",
// },
// {
//     id: 2,
//     name: "Joey Tribbiani",
//     username: "JoeyT",
//     email: "JoeyT@test.com",
//     profilePicture: "/assets/person/joey.jpg",
// },
// {
//     id: 3,
//     name: "Monica Geller",
//     username: "Mgeller",
//     email: "Mgeller@test.com",
//     profilePicture: "/assets/person/monica_geller.jpg",
// },
// {
//   id: 4,
//   name: "Phoebe Buffay",
//   username: "PhoebeB",
//   email: "PhoebeB@test.com",
//   profilePicture: "/assets/person/Phoebe.jpg",
// },
// {
//   id: 5,
//   name: "Rachel Green",
//   username: "Rgreen",
//   email: "Rgreen@test.com",
//   profilePicture: "/assets/person/rachel.jpg",
// },
// {
//   id: 6,
//   name: "Ross Geller",
//   username: "Rgeller",
//   email: "Rgeller@test.com",
//   profilePicture: "/assets/person/RossGeller.jpg",
// },
// ];

export const posts = [
    {
      id: 1,
      desc: "Let's Celebrate",
      photo: "assets/postImages/01.jpg",
      date: "10 mins ago",
      userId: 1,
      like: 52,
      comment: 20,
    },
    {
      id: 2,
      desc: "Friends is all you need!",
      photo: "assets/postImages/02.jpg",
      date: "15 mins ago",
      userId: 2,
      like: 31,
      comment: 10,
    },
    {
      id: 3,
      desc: "Live Love Laugh.",
      photo: "assets/postImages/03.jpg",
      date: "3 hour ago",
      userId: 3,
      like: 56,
      comment: 39,
    },
    {
      id: 4,
      desc: "Dress Your Best! Its Halloween!",
      photo: "assets/postImages/04.jpg",
      date: "2 hours ago",
      userId: 4,
      like: 28,
      comment: 12,
    },
    {
      id: 5,
      desc: "Let's Play A Game",
      photo: "assets/postImages/05.jpg",
      date: "1 hours ago",
      userId: 5,
      like: 17,
      comment: 3,
    },
    {
        id: 6,
        desc: "My Tribe",
        photo: "assets/postImages/06.jpg",
        date: "2 days ago",
        userId: 6,
        like: 54,
        comment: 16,
      },
];